import { Problem } from '@/services/core/type';

type UserRole =
  | 'PERMISSION_SUPER_USER'
  | 'PERMISSION_BASIC_USER'
  | 'PERMISSION_PAGE_DATA_BANK_PERSON'
  | 'PERMISSION_PERSON_ADD_BATCH'
  | 'PERMISSION_PERSON_ADD_SINGLE'
  | 'PERMISSION_PERSON_EDIT'
  | 'PERMISSION_PERSON_DELETE'
  | 'PERMISSION_PAGE_CAMERA_MANAGEMENT'
  | 'PERMISSION_CAMERA_ADD'
  | 'PERMISSION_CAMERA_EDIT'
  | 'PERMISSION_CAMERA_DELETE'
  | 'PERMISSION_PAGE_DATA_BANK_GROUP'
  | 'PERMISSION_GROUP_ADD'
  | 'PERMISSION_GROUP_EDIT'
  | 'PERMISSION_GROUP_DELETE'
  | 'PERMISSION_PAGE_WATCHLIST'
  | 'PERMISSION_WATCHLIST_ADD'
  | 'PERMISSION_WATCHLIST_EDIT'
  | 'PERMISSION_WATCHLIST_DELETE'
  | 'PERMISSION_PAGE_MODULE_MANAGEMENT'
  | 'PERMISSION_MODULE_ADD'
  | 'PERMISSION_MODULE_EDIT'
  | 'PERMISSION_MODULE_DELETE'
  | 'PERMISSION_PAGE_USER_MANAGEMENT'
  | 'PERMISSION_USER_ADD'
  | 'PERMISSION_USER_EDIT'
  | 'PERMISSION_USER_DELETE'
  | 'PERMISSION_PAGE_CAMERA_VIEW_CAMERA'
  | 'PERMISSION_PAGE_CAMERA_VIEW_EVENT'
  | 'PERMISSION_PAGE_INVESTIGATION_VIDEO'
  | 'PERMISSION_PAGE_INVESTIGATION_IMAGE'
  | 'PERMISSION_PAGE_REPORT_REPORT'
  | 'PERMISSION_PAGE_REPORT_GRAPH'
  | 'PERMISSION_PAGE_SETTING_GENERAL'
  | 'PERMISSION_PAGE_SETTING_BACKUP';

export type OperationResult<T> = {
  isSuccess: boolean;
  error?: Problem | string;
  response?: T | void;
};

export interface UserResponse {
  id: number;
  username: string;
  roles: UserRole[];
  description?: string;
  detail?: string;
}

export type TUserModel = {
  username: string;
  password: string;
};
