import { CellType } from '@/components/CustomTable/types';
import { ReportRoute } from '@/strings';

export const defaultArrivalsAndDeparturesModalPicFormValues = {
  ArrivalGateName: '',
  ArrivalGateOrientation: '',
  TimeOf: '',
  TimeTo: '',
};

export const COLLAPSE_ID = 'collapse';

export const ArrivalsAndDeparturesMockData = [
  {
    id: 1,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 2,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 3,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 4,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 5,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 6,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 7,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 8,
    ArrivalGateName: 'Gate probox 1.1-2',
    ArrivalGateOrientation: 'ورودی',
    ArrivalTime: '8:10',
    ExitGateName: 'Gate probox 1.1-2',
    ExitGateOrientation: 'خروجی',
    ExitTime: '14:32',
    MatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
];

export const ArrivalsAndDeparturesHeader: CellType[] = [
  {
    id: COLLAPSE_ID,
    label: '',
  },
  {
    id: 'ArrivalGateName',
    label: ReportRoute.ArrivalGateName,
    sortable: true,
  },
  {
    id: 'ArrivalGateOrientation',
    label: ReportRoute.ArrivalGateOrientation,
    sortable: true,
  },
  {
    id: 'ArrivalTime',
    label: ReportRoute.ArrivalTime,
    sortable: true,
  },
  {
    id: 'ExitGateName',
    label: ReportRoute.ExitGateName,
    sortable: true,
  },
  {
    id: 'ExitGateOrientation',
    label: ReportRoute.ExitGateOrientation,
    sortable: true,
  },
  {
    id: 'ExitTime',
    label: ReportRoute.ExitTime,
    sortable: true,
  },
  {
    id: 'MatchPercentage',
    label: ReportRoute.MatchPercentage,
    sortable: true,
  },
];
