import { CellType } from '@/components/CustomTable/types';
import { ReportRoute } from '@/strings';

export const defaultArrivalsAndDeparturesModalPicFormValues = {
  arrivalsAndDeparturesَArrivalGateName: '',
  arrivalsAndDeparturesArrivalGateِOrientation: '',
  arrivalsAndDeparturesTimeOf: '',
  arrivalsAndDeparturesTimeTo: '',
};

export const COLLAPSE_ID = 'collapse';

export const ArrivalsAndDeparturesَMockData = [
  {
    id: 1,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 2,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 3,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 4,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 5,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 6,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 7,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 8,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 9,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
  {
    id: 10,
    arrivalsAndDeparturesَArrivalGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesArrivalGateِOrientation: 'ورودی',
    arrivalsAndDeparturesَArrivalTime: '8:10',
    arrivalsAndDeparturesExitGateName: 'Gate probox 1.1-2',
    arrivalsAndDeparturesExitGateِOrientation: 'خروجی',
    arrivalsAndDeparturesَExitTime: '14:32',
    arrivalsAndDeparturesMatchPercentage: '95.56٪',
    age: '25',
    gender: 'مرد با احتمال بالا',
    matchCount: '1',
  },
];

export const ArrivalsAndDeparturesَHeader: CellType[] = [
  {
    id: COLLAPSE_ID,
    label: '',
  },
  {
    id: 'arrivalsAndDeparturesَArrivalGateName',
    label: ReportRoute.arrivalsAndDeparturesَArrivalGateName,
    sortable: true,
  },
  {
    id: 'arrivalsAndDeparturesArrivalGateِOrientation',
    label: ReportRoute.arrivalsAndDeparturesArrivalGateِOrientation,
    sortable: true,
  },
  {
    id: 'arrivalsAndDeparturesَArrivalTime',
    label: ReportRoute.arrivalsAndDeparturesَArrivalTime,
    sortable: true,
  },
  {
    id: 'arrivalsAndDeparturesExitGateName',
    label: ReportRoute.arrivalsAndDeparturesExitGateName,
    sortable: true,
  },
  {
    id: 'arrivalsAndDeparturesExitGateِOrientation',
    label: ReportRoute.arrivalsAndDeparturesExitGateِOrientation,
    sortable: true,
  },
  {
    id: 'arrivalsAndDeparturesَExitTime',
    label: ReportRoute.arrivalsAndDeparturesَExitTime,
    sortable: true,
  },
  {
    id: 'arrivalsAndDeparturesMatchPercentage',
    label: ReportRoute.arrivalsAndDeparturesMatchPercentage,
    sortable: true,
  },
];
