/** ********** GENERAL ********** */

export const generalStr = {
  matchCount: 'تعداد تطبیق',
  creditFrom: 'مقدار اعتبار از',
  creditTo: 'مقدار اعتبار تا',
  expireTimeFrom: 'تاریخ انقضاء از',
  expireTimeTo: 'تاریخ انقضاء تا',
  numOfAllCapacityFrom: 'تعداد کل ظرفیت از',
  numOfAllCapacityTo: 'تعداد کل ظرفیت تا',
  numOfUseFrom: 'تعداد استفاده شده از',
  numOfUseTo: 'تعداد استفاده شده تا',
  remainCapacityFrom: 'ظرفیت باقی‌مانده از',
  remainCapacityTo: 'ظرفیت باقی‌مانده تا',
  faq: 'سوالات متداول',
  settings: 'تنظیمات',
  rankFrom: 'ترتیب نمایش از',
  rankUpTo: 'ترتیب نمایش تا',
  collapseMenu: 'جمع شدن منو',
  openMenu: 'باز شدن منو',
  englishName: 'نام انگلیسی',
  placeholderDatepicker: 'روز/ماه/سال',
  dashboard: 'داشبورد',
  logout: 'خروج از حساب کاربری',
  increaseCredit: 'افزایش اعتبار',
  createNewCategory: 'ایجاد دسته‌بندی جدید',
  normal: 'عادی',
  pleaseBePatient: 'لطفاً شکیبا باشید.',
  reservation: 'رزرو',
  fillingThisFieldIsNecessary: 'پر کردن این قسمت ضروری است',
  successfullyAdded: 'با موفقیت اضافه شد.',
  thereIsAProblem: 'مشکلی پیش آمده',
  editSuccessfully: 'با موفقیت ویرایش شد.',
  successfullyRemoved: 'با موفقیت حذف شد.',
  collectionName: 'نام مجموعه',
  tooManyCharacters: 'تعداد کاراکترها بیش از حد مجاز است',
  select: 'انتخاب کنید',
  requiredField: 'فیلد اجباری',
  condition: 'وضعیت',
  conditionEqual: 'وضعیت:',
  submit: 'ثبت',
  applyChanges: 'اعمال تغییرات',
  refuse: 'انصراف',
  categoryName: 'نام دسته‌بندی',
  registeryDate: 'تاریخ عضویت',
  lastEdition: 'آخرین ویرایش',
  add: 'افزودن',
  edit: 'ویرایش',
  number: 'تعداد',
  category: 'دسته‌بندی',
  registrationCompletedSuccessfully: 'ثبت با موفقیت انجام شد.',
  thisFieldIsRequired: 'درج این فیلد ضروریست',
  noData: 'اطلاعاتی موجود نیست',
  brand: 'برند',
  model: 'مدل',
  deviceId: 'شناسه دستگاه',
  deviceIp: 'آی پی دستگاه',
  charactersMoreThanThirty: 'تعداد کارکتر بیش از 30 باشد.',
  charactersLessThanSixty: 'تعداد کارکتر کمتر از 60 باشد.',
  hoursOfUse: 'ساعت استفاده',
  startTime: 'زمان شروع به کار',
  getStarted: 'شروع به کار',
  confirmation: 'تأیید',
  cancel: 'لغو',
  erase: 'پاک کردن',
  today: 'امروز',
  unattached: 'آزاد',
  inUse: 'در حال استفاده',
  search: 'جست و جو کنید ...',
  tags: 'تگ ها',
  rankToDisplayOrder: 'رنک جهت ترتیب نمایش',
  viewOrder: 'ترتیب نمایش',
  numberLessThanThousand: 'عددی کمتر از 1000 وارد نمائید.',
  numberGreaterThanZero: 'عددی بیشتر از 0 وارد نمائید.',
  description: 'توضیحات',
  firstCharge: 'شارژ اولیه',
  createdDate: 'تاریخ ایجاد',
  pictureUploadFormatError: `فایل باید شامل یکی از فرمت های 'jpg/jpeg/png' باشد`,
  uploadFileSizeLimit: 'فایل با حجم کمتر از 5مگابایت آپلود کنید.',
  clickToSelectFile: 'برای انتخاب فایل کلیک کنید.',
  changesMadeSuccessfully: 'تغییرات با موفقیت انجام شد.',
  editGiftCodeWasSuccess: 'ویرایش کد هدیه با موفقیت انجام شد.',
  addNewItem: 'افزودن مورد جدید',
  title: 'عنوان',
  titleRequired: 'درج عنوان ضروریست',
  aswer: 'پاسخ',
  frequentlyAskedQuestions: 'سؤالات متداول',
  requests: 'درخواست ها',
  listOfBanks: 'لیست بانک‌ها',
  back: 'بازگشت',
  campaigns: 'کمپین ها',
  bankName: 'نام بانک',
  apiName: 'نام API',
  operations: 'عملیات',
  accepted: 'تایید شده',
  unableToRejectApi: 'عدم امکان مردود کردن API',
  activeUserInfo: 'این API دارای کاربر فعال می‌‌باشد.',
  unableToRejectApiInfo: 'در حال حاضر امکان مردود کردن آن فراهم نمی‌باشد.',
  messageToTheProvider: 'پیام به ارائه دهنده',
  messageTitle: 'عنوان پیام',
  time: 'زمان',
  defaultHelpText: 'متن راهنما پیش فرض',
  typeOfTransaction: 'نوع تراکنش',
  amountRials: 'مبلغ(ریال)',
  cancelWithdrawalRquestFromAccount: 'لغو درخواست برداشت از حساب',
  statusReport: 'صورت وضعیت',
  hourlyUsagePrice: 'قیمت استفاده ساعتی',
  gpuCategory: ' دسته GPU ',
  furtherDetails: 'توضیحات تکمیلی',
  month: 'ماه',
  months: 'ماهه',
  packageValidityPeriod: 'مدت اعتبار بسته',
  storageMemory: 'حافظه ذخیره‌سازی',
  unlimited: 'بدون محدودیت',
  numberPerDay: 'عدد در روز',
  maximumCallsPerDay: 'بیشینه تعداد فراخوانی در هر روز',
  thousandRials: 'هزار ریال',
  free: 'رایگان',
  packageInputPrice: 'قیمت ورودی بسته',
  cpuOnly: 'فقط CPU',
  packageTime: 'زمان بسته',
  entranceFee: 'هزینه ورودی',
  hourlyCostOfGraphicComputing: 'هزینه استفاده ساعتی رایانش گرافیکی',
  numberOfCall: 'تعداد فراخوانی',
  packageSpecifications: 'مشخصات بسته',
  activePackage: 'بسته فعال',
  activeGpuPackage: 'بسته پردازش گرافیکی فعال',
  used: 'استفاده شده',
  notUsed: 'استفاده نشده',
  reserved: 'رزرو شده',
  new: 'جدید',
  creation: 'ایجاد',
  invitationCode: 'کد دعوت',
  invitationCodes: 'کدهای دعوت',
  giftCode: 'کد هدیه',
  creditAmountRial: 'مقدار اعتبار(ریال)',
  creditAmountToman: 'مقدار اعتبار(تومان)',
  approveChanges: 'ثبت تغییرات',
  expirationDate: 'تاریخ انقضاء',
  user: 'کاربر',
  successful: 'موفق',
  unsuccessful: 'ناموفق',
  signIn: ' وارد شوید ',
  lastaAccess: 'آخرین دسترسی',
  active: 'فعال',
  inactive: 'غیر فعال',
  deletionSuccessful: 'حذف با موفقیت انجام شد.',
  name: 'نام',
  lastName: 'نام خانوادگی',
  processing: 'در حال پردازش',
  home: 'خانه',
  graphicComputing: 'رایانش گرافیکی',
  gpuClassification: 'دسته‌بندی GPU',
  hardWare: 'سخت‌افزار',
  marketApi: 'API مارکت',
  collection: 'کالکشن',
  categoryFi: 'کتگوری',
  aiBoxPlatform: ' پلتفرم AIBOX',
  aiService: 'سرویس AI',
  financialDepartment: 'امور مالی',
  transactions: 'تراکنش‌ها',
  packages: 'بسته‌ها',
  support: 'پشتیبانی',
  rules: 'قوانین',
  collectMenu: 'جمع کردن منو',
  helpEn: 'help',
  settingEn: 'setting',
  emailEn: 'Email',
  gbEn: 'GB',
  gddrEn: 'GDDR',
  coresEn: 'Cores',
  cudaCoresEn: 'Cuda cores',
  ipEn: 'ip',
  idEn: 'id',
  cpu: 'CPU',
  gpu: 'GPU',
  // use
  apiPresentationPlatform: 'پلتفرم ارائه API',
  cloudGraphicProcessing: 'پردازش گرافیکی ابری',
  artificialIntelligenceServices: 'سرویس های هوش مصنوعی',
  aiPlatform: 'پلتفرم ارائه های هوش مصنوعی',
  sendMessage: 'ارسال پیام',
  realized: 'متوجه شدم',
  moreDetails: 'توضیحات بیشتر',
  signUpForFree: 'رایگان ثبت نام کنید.',
  registerNow: 'همین حالا ثبت نام گنید.',
  viewTheListOfApis: 'مشاهده لیست API‌ها',
  viewPackages: 'مشاهده بسته ها',
  aiPlatformApi: 'پلتفرم ارائه ‌APIهای هوش مصنوعی',
  nextera: 'نکسترا',
  productIntroduction: 'معرفی محصولات',
  services: 'خدمات',
  aiBox: 'ای آی باکس',
  aboutUs: 'درباره ما',
  contactUs: 'تماس با ما',
  siteMap: 'نقشه سایت',
  advancedSearch: 'جستجوی پیشرفته',
  amount: 'مبلغ',
  price: 'قیمت',
  priceEqual: 'قیمت:',
  priceToman: 'مبلغ(تومان)',
  notFound: 'موردی یافت نشد',
  version: 'نسخه',
  from: 'از',
  to: 'به',
  upTo: 'تا',
  currency: 'هزار تومان',
  service: 'سرویس',
  type: 'تایپ کنید',
  filterByDate: 'فیلتر بر اساس تاریخ',
  filterByTopic: 'فیلتر بر اساس موضوع',
  filterByAmount: 'فیلتر بر اساس مبلغ',
  applyFilter: 'اعمال فیلتر',
  filter: 'فیلتر',
  enTrue: 'true',
  enFalse: 'false',
  enUsed: 'used',
  enUnUsed: 'unused',
  enAssigned: 'assigned',
  payment: 'پرداخت',
  profile: 'پروفایل',
  files: 'فایل ها',
  wallet: 'کیف پول',
  announcements: 'اعلان ها',
  changePassword: 'تغییر گذرواژه',
  factors: 'فاکتورها',
  titleTitle: 'عنوان(تیتر)',
  upgradePackages: 'ارتقا بسته',
  toman: 'تومان',
  returnToPreviousStep: 'بازگشت به مرحله قبل',
  fromTheBeginning: 'از ابتدا',
  yesterday: 'روز گذشته',
  lastWeek: 'هفته گذشته',
  lastMonth: 'ماه گذشته',
  lastYear: 'سال گذشته',
  creditsEarned: 'اعتبار کسب شده',
  dontWantToSay: 'تمایل به گفتن ندارم',
  responseError: 'مشکلی رخ داده است',
  nameIsRequired: 'درج نام ضروریست',
  errors: 'خطاها',
  operationForm: 'صورت عملیات',
  changeSuccessfully: 'تغییر با موفقیت انجام شد',
  fieldIsRequired: 'پر کردن فیلد الزامی است',
  explanationText: 'متن توضیح',
  logoImage: 'تصویر لوگو',
  thisFieldIsNecessary: '(پر کردن این قسمت ضروریست)',
  insert: 'درج',
  itIsNecessary: 'ضروریست',
  endpointName: 'نام Endpoint',
  method: 'متد',
  briefExplanation: 'توضیح مختصر',
  briefExplanationRequired: 'درج توضیح مختصر ضروریست',
  enterTheValueOfThisFieldIsRequired: 'وارد کردن مقدار این فیلد الزامیست',
  thereIsProblem: 'مشکلی پیش آمده است.',
  shouldNotStartWithZero: 'مبلغ نباید با صفر شروع شود.',
  cardNumber: 'شماره کارت',
  shabaNumber: 'شماره شبا',
  bankInformation: 'اطلاعات بانکی',
  reportRequest: 'گزارش درخواست‌ها',
  value: 'مقدار',
  apiRemovalWasSuccessful: 'حذف API با موفقیت انجام شد',
  searchPlaceHolder: 'جستجوی اندپوینت ...',
  codeAddress: 'آدرس کد',
  dockerImageAddress: 'آدرس داکر ایمیج',
  gitUrl: 'آدرس URL گیت',
  zipUrl: 'آدرس URL زیپ',
  port: 'پورت',
  updated: 'بروزرسانی شده است.',
  statisticsAndInformation: 'آمار و اطلاعات',
  package: 'بسته',
  selectPackage: 'انتخاب بسته',
  areYouSure: 'آیا مطمئن هستید؟',
  theAmountPayable: 'مبلغ قابل پرداخت',
  acceptPackageRules: 'قوانین بسته‌ها را می‌پذیرم.',
  viewRules: 'مشاهده قوانین',
  addEndpoint: 'افزودن Endpoint ',
  addEndpoints: 'افزودن EndPoint ها',
  maximumFiftyCharacters: 'حداکثر 50 کارکتر',
  cancelEdit: 'لغو ویرایش',
  changeThePackage: 'تغییر بسته',
  recivingInformation: 'دریافت اطلاعات',
  diployResult: 'نتیجه دیپلوی',
  endpointTesting: 'تست EndPoint ها',
  uploadNewFile: 'بارگذاری فایل جدید',
  email: 'ایمیل',
  forgotPassHelper:
    'گذرواژه باید حداقل 8 کاراکتر و حاوی حروف بزرگ و کوچک لاتین باشد.',
  passwordDoesNotMatch: 'رمز عبور مطابقت ندارد',
  selectFolderName: 'انتخاب نام پوشه',
  folderName: 'نام پوشه',
  maximumThirtyCharacters: 'حداکثر کاراکتر مجاز 30 کاراکتر می‌باشد.',
  cancelOperation: 'لغو عملیات',
  continue: 'ادامه دادن',
  accountNumer: 'شماره حساب',
  delete: 'حذف',
  yes: 'بله',
  apiEn: 'API',
  errorEn: 'error',
  typeEN: 'type',
  labelTextEn: 'labelText',
  categoryEn: 'category',
  apiKeyEn: 'API key',
  headerEn: 'Header',
  headersEn: 'Headers',
  bodyEn: 'Body',
  queryStringEn: 'Query String',
  schemaEn: 'Schema',
  exampleResponseEn: 'Example Response',
  enterJsonDataEn: 'please enter the JSON data ...',
  codeSnippetEn: 'Code Snippet',
  collectionEn: 'collection',
  payAsYouGoEn: 'PAY AS YOU GO',
  selectFileEn: 'select file',
  cudaEn: 'cuda',
  foldersEn: 'Folders',
  access: 'دسترسی',
  admin: 'ادمین',
  firstOption: 'گزینه اول',
  secondOption: 'گزینه دوم',
  autoCompleteEn: 'autocomplete',
  label: 'لیبل',
  ticketing: 'تیکت‌ها',
  improving: '(در حال توسعه)',
  closeMenu: 'جمع‌شدن منو',
  amountOfAllCapacity: 'تعداد کل ظرفیت',
  remainCapacity: 'ظرفیت باقی‌مانده',
  createdTimeFrom: 'تاریخ ایجاد از',
  createdTimeUpTo: 'تاریخ ایجاد تا',
  updatedTimeFrom: 'آخرین ویرایش از',
  updatedTimeUpTo: 'آخرین ویرایش تا',
  deleteModalDescription:
    'با پاک کردن این مورد تمامی اطلاعات آن‌ از بین خواهد رفت.',
  users: 'کاربران',
  haveIt: 'دارد',
  haveNot: 'ندارد',
  maxIsTowThousand: 'این مقدار باید کوچکتر یا مساوی ۲۰۰۰ باشد',
  maxNumberMustBeTowThousand: 'این مقدار باید کوچکتر یا مساوی ۲۰۰۰ باشد',
  MaxChargeMustBeOneMillion:
    'مقدار شارژ اولیه باید کوچکتر یا مساوی با 100,000,000 تومان باشد.',
  startDateLowerThanEndDate: 'تاریخ شروع نمی تواند از تاریخ پایان بزرگتر باشد.',
  numberPersons: 'تعداد افراد عبوری',
  clientState: 'وضعیت کلاینت‌ها',
  gender: 'جنسیت افراد ثبت نامی',
  ageRange: 'بازه‌ی سنی افراد عبوری',
  stateList: 'وضعیت لیست‌های نظارتی',
  registeredPeople: 'افراد ثبت نامی',
  transientPeople: 'افراد عبوری',
  waitinglists: 'تعداد لیست انتظار',
  numberClients: 'تعداد کلاینت‌ها',
};

export const registrationStr = {
  changePass: 'تغییر گذرواژه',
  login: 'ورود',
  register: 'ثبت نام',
  signOut: 'خارج شوید',
  username: 'نام کاربری',
  email: 'ایمیل',
  password: 'گذرواژه',
  roobinPassword: 'رمز عبور',
  newPass: 'گذرواژه جدید',
  ReNewPass: 'تکرار گذرواژه جدید',
  ok: 'تائید',
  accountActivation: 'فعال سازی حساب کاربری',
  successResendEmailActivate: 'ایمل فعالسازی با موفقیت ارسال شد.',
  successResendPhoneActivate: 'شماره موبایل شما با موفقیت تأیید شد.',
  successResendPhoneActivateV2: 'شماره موبایل شما با موفقیت فعال شد.',
  userNotFound: 'کاربری با این مشخصات یافت نشد.',
  changePasswordIsDone: 'کلمه عبور شما با موفقیت تغییر یافت.',
  newPassword: 'کلمه عبور جدید',
  addNewPassword: 'لطفاً کلمه عبور جدیدی برای خود انتخاب و وارد کنید.',
  goToLogin: 'رفتن به صفحه ورود',
  accountIsNotAct: 'حساب کاربری شما فعال نشده است.',
  mobileIsNotAct: 'شماره موبایل شما فعال نشده است.',
  notActiveMobileDescription: 'ابتدا باید شماره موبایل خود را فعال کنید.',
  activePhoneNumber: 'فعالسازی شماره موبایل',
  recoveryWithEmailOurPhoneNumber:
    'با استفاده از «شماره موبایل» یا «ایمیل»، کلمه عبور خود را بازیابی کنید.',
  emailOurPhoneNumber: 'شماره موبایل/ایمیل',
  changePhoneNumber: 'تغییر شماره موبایل',
  resendCode: 'ارسال مجدد کد',
  logInWithAOneTimePassword: 'ورود با رمز یکبارمصرف',
  securityCode: 'کد امنیتی',
  rules: 'قوانین',
  acceptRules: 'AIBox را مطالعه کرده‌ام و قبول دارم.',
  addYourInformation: 'اطلاعات خود را وارد نمایید.',
  createAnAccount: 'ایجاد حساب کاربری',
  accountCreationSuccessfully: 'ایجاد حساب کاربری با موفقیت انجام شد.',
  logOut: 'خروج',
  registerPhoneNumber: 'ثبت شماره موبایل',
  signIn: 'وارد شوید',
  forgotPass: 'کلمه عبور خود را فراموش کرده‌اید؟',
  forgotPassHelper:
    'کلمه عبور باید حداقل 8 کاراکتر و حاوی حروف بزرگ و کوچک لاتین باشد.',
  resetPass: 'بازیابی کلمه عبور',
  resetPassword: 'بازیابی کلمه عبور',
  interNewPass: 'کلمه عبور جدید را وارد نمایید.',
  resetPassTitle: 'کلمه عبور خود را فراموش کرده‌اید؟',
  resetPassDesc:
    'برای بازیابی آن، لطفاً آدرس ایمیل مرتبط با حساب کاربری خود را وارد کنید.',
  acceptRole: 'قوانین را می‌پذیرم.',
  acceptRoleBeforLink: 'شما با ثبت نام در AIBox',
  acceptRoleLink: 'شرایط استفاده از خدمات',
  acceptRoleAfterLink: ' را می‌پذیرید.',
  remmeberMe: 'مرا بخاطر بسپار',
  loginGoogle: 'با حساب گوگل خود وارد شوید.',
  registerGoogle: 'با حساب گوگل خود ثبت نام کنید.',
  notRegister: 'هنوز حساب کاربری ندارید؟',
  notRegisterV2: ' حساب کاربری ندارید؟',
  registration: ' ثبت نام کنید. ',
  smaePassErr: 'کلمه عبور باید یکسان تکرار شود.',
  passRequiredErr: 'درج کلمه عبور الزامیست.',
  emailRequiredErr: 'درج ایمیل الزامیست.',
  emailNotValidErr: 'ایمیل بدرستی وارد نشده است.',
  isRegisterBefor: 'قبلا ثبت نام کردید؟',
  returnToLogin: 'بازگشت به صفحه ورود',
  sucsessMsgPart3:
    'جهت استفاده از کلیه امکانات سایت باید حساب کاربری خود را فعال کنید.',
  verficationg: 'در حال صحت‌سنجی اطلاعات، لطفا شکیبا باشید.',
  youAreRegistered: 'حساب کاربری شما با موفقیت ثبت شد. وارد شوید.',
  newPassSeted: 'کلمه عبور شما با موفقیت تغییر کرد. وارد شوید.',
  sucsessMsgPart1: 'عزیز، با تشکر از ثبت نام شما در AIBox',
  emailSentSuccessfully: 'ایمیل با موفقیت ارسال شد.',
  sent: 'ارسال شد',
  successMessagepart2: 'لینک فعالسازی حساب کاربری شما، به آدرس ایمیل',
  enterEmailRequired: 'وارد کردن ایمیل الزامیست.',
  tessera: 'کلمه عبور',
  passwordRequired: 'وارد کردن کلمه عبور الزامیست.',
  repeatPassword: 'تکرار کلمه عبور',
  invitationCode: 'کد دعوت',
  invitationCodeRequired: 'وارد کردن کد دعوت الزامیست.',
  resendActivationEmail: 'ارسال مجدد ایمیل فعال سازی',
  withRegisteredInAiBox: 'شما با ثبت نام در AIBox',
  accept: 'را می‌پذیرید.',
  dontReciveActivationEmail: 'ایمیل فعالسازی را دریافت نکرده‌اید؟',
  resend: 'ارسال مجدد',
  enterYourEmailAddress: 'آدرس ایمیل خود را وارد کنید.',
  loginToaccunt: 'ورود به حساب کاربری',
  passwordRecovery: 'بازیابی کلمه عبور',
  forgotPassword: 'فراموشی  کلمه عبور',
  emailIsNotAct: 'ایمیل شما فعال نشده است.',
  phoneNumberIsNotAct: 'شماره موبایل ثبت نشده است.',
  actPhoneNumber: 'فعالسازی شماره موبایل',
  onlySevenCharacter: 'تعداد کاراکتر 7 عدد می‌باشد.',
  captchaRequierd: 'کد امنیتی اشتباه می‌باشد.',
  notifications: 'اعلان‌ها',
  panelGuide: 'راهنمای کار با پنل',
};

export const messageStr = {
  emailNotValid: 'ایمیل صحیح نمی باشد',
  fieldIsEmpty: 'این فیلد نباید خالی باشد',
  fieldNotCorrect: 'فرمت این فیلد صحیح نمی باشد',
  passNotSrong: 'گذرواژه قوی نمی باشد',
  responseFailed: ' متاسفانه مشکلی رخ داده است. لطفا وقت دیگری را امتحان کنید!',
  responseGlFailed:
    ' متاسفانه مشکلی رخ داده است. لطفا راه دیگری را امتحان کنید!',
  loginSuccess: 'شما با موفقیت وارد شدید',
  registerSuccess: 'ثبت نام با موفقیت انجام شد. لطفا وارد شوید',
  checkEmail: 'لینک ارسال شد. لطفا ایمیل خود را چک کنید.',
  passNotEqual: 'تکرار گذرواژه با گذرواژه وارد شده همخوانی ندارد',
  youAreNotAllowed: 'شما دسترسی به این صفحه را ندارید',
  loginWithUsername: 'با حساب کاربری خود وارد شوید.',

  youNotAdmin:
    'شما دسترسی به این بخش را ندارید ، برای ورود به بخش خود دکمه ی زیر را کلیک نمائید',
  returnToHome: 'بازگشت به خانه',
  notFound: 'صفحه مورد نظر یافت نشد',
  serverSideError: 'در سمت سرور مشکلی وجود دارد',
  pleaseWait: 'متخصصین ما در حال رفع مشکل هستند، از شکیبایی شما سپاس‌گذاریم',
  notAccessToProfile: 'در حال حاضر دسترسی پروفایل امکان ندارد.',
  isLogOut: 'خارج می‌شوید؟  ',
};

export const termsAndPoliciesStr = {
  title: 'قوانین و شرایط استفاده',
  joinNow1: 'همین حالا به خانواده AI BOX ملحق شو',
  joinNow2: 'ها API ورود به دنیای',
};

/** ********** GRAPHIC COMPUTING ********** */

// GPU CATEGORY
export const gpuCategoryStr = {
  gpuClassificationList: 'لیست دسته‌بندی GPU ها',
  warranty: 'گارانتی',
  deleteCategory: 'حذف کردن دسته',
  defineANewCategory: 'تعریف دسته جدید',
  editCategory: 'ویرایش دسته',
  collectionNameRequired: 'درج نام مجموعه ضروریست',
  selectGpus: 'انتخاب GPU ها',
  rank: 'رنک',
  listOfGpus: 'لیست GPUها',
  gpus: 'GPUها',
  discs: 'دیسک ها',
  configurations: 'پیکربندی ها',
  usersPackages: 'بسته های کاربران',
  servers: 'سرورها',
  users: 'کاربران',
  noProcrastinationNoInterruption: 'بدون معطلی، بدون قطع شدن',
  withDelayThePossibilityOfInterruption: 'با معطلی، امکان قطع شدن',
  withDelayNoInterruption: 'با معطلی، بدون قطع شدن',
  number: 'عدد',
};

// HARDWARE
export const hardWare = {
  addNewGpu: 'افزودن GPU جدید',
  addNewCpu: 'افزودن CPU جدید',
  memory: 'حافظه',
  cpuWasRemoved: 'cpu مورد نظر حذف شد.',
  specifications: 'مشخصات',
  numberOfCores: 'تعداد هسته',
  coreThreadsEn: 'Cores/Threads',
  maxBoostGhzEn: 'Max Boost(GHz)',
  maxBoostEn: 'Max Boost',
  baseClockGhzEn: 'Base Clock(GHz)',
  baseClockEn: 'base clock',
  threadsEn: 'Threads',
  cacheMbEn: 'Cache(MB)',
  cacheEn: 'Cache',
  hardWareEn: 'Hardware',
};

/** ********** API MARKET ********** */

// COLLECTION
export const apiMarketCollection = {
  createNewCollection: 'ایجاد مجموعه جدید',
  addNewCollection: 'افزودن مجموعه جدید',
  collection: 'مجموعه',
  collections: 'مجموعه‌ها',
  editCollection: 'ویرایش مجموعه',
  minimumNumberOfRequests: 'حداقل تعداد درخواست',
  minimumNumberOfUsers: 'حداقل تعداد کاربران',
  orderBy: 'مرتب سازی بر اساس',
  dateSelection: 'انتخاب تاریخ',
  ascending: 'صعودی',
  descending: 'نزولی',
  minimumApiRating: 'حداقل امتیاز API',
  fiveAs: '5/',
  requestsEn: 'REQUESTS',
  enrollEn: 'ENROLL',
  dateEn: 'DATE',
  ratingEn: 'RATING',
  alphabetEn: 'ALPHABET',
  categories: 'دسته‌بندی‌ها',
};

// CATEGORY
export const apiMarketCategory = {
  categories: 'دسته‌بندی‌ها',
  categoryDeleted: 'کتگوری مورد نظر حذف شد.',
  editCategories: 'ویرایش دسته‌بندی',
  addNewCategory: 'افزودن دسته‌بندی جدید',
  image: 'تصویر',
};

// TOS
export const tosString = {
  newTosAdded: 'TOS جدید اضافه شد.',
  tosWasRemoved: 'TOS مورد نظر حذف شد.',
  descriptionRequired: 'درج توضیحات ضروریست',
};

// FAQ
export const faqString = {
  newFaqAdded: 'faq جدید اضافه شد.',
  faqWasRemoved: 'faq مورد نظر حذف ش.',
  question: 'سوال',
  questionRequired: 'درج سوال ضروریست',
  group: 'گروه',
  groupNameRequired: 'درج نام گروه ضروریست',
  answerRequired: 'درج پاسخ ضروریست',
};

// BANK
export const bankString = {
  createNewBank: 'ایجاد بانک جدید',
  newNameIsSameAsPreviousOne: 'نام جدید با نام قبلی یکی است',
  newBankAdded: 'بانک جدید اضافه شد',
  addNewBank: 'افزودن بانک جدید',
};

// AI SERVICE
export const aiServiceString = {
  aiServices: 'سرویس‌های Ai',
  collections: 'کالکشن',
  category: 'کتگوری',
  servers: 'سرورها',
  apiPark: 'API پارک',
  users: 'کاربران',
  provider: 'ارائه‌دهنده',
  dateOfApproval: 'تاریخ کسب  تأییدیه',
  numberOfRegistrations: 'تعداد ثبت نام',
  totalCall: 'مجموع فراخوانی',
  rejected: 'مردود',
  reject: 'مردود کردن',
  confirm: 'تایید کردن',
  sender: 'ارسال کننده',
  developed: 'توسعه داده شده',
  updatedOn: 'به روزرسانی شده در',
  viewApiPage: 'مشاهده صفحه API',
  rejectApi: 'مردود کردن API',
  confirmApi: 'تایید کردن API',
  createdOn: 'ایجاد شده در تاریخ',
  verificationProcess: 'فرآیند تأیید',
};

export const apiPlatformStr = {
  apiPresentationPlatform: 'پلتفرم ارائه API',
  apis: 'API ها',
  status: 'صورت وضعیت',
  servers: 'سرورها',
  users: 'کاربران',
};

export const financeStr = {
  finance: 'امور مالی',
  transactions: 'تراکنش ها',
  invitationCodes: 'کد دعوت',
  giftCodes: 'کد هدیه',
  bankList: 'لیست بانک ها',
};

export const supportStr = {
  support: 'پشتیبانی',
  faqs: 'سوالات متداول',
  termsAndAgreements: 'قوانین و شرایط استفاده',
  tickets: 'تیکت ها',
};

export const marketingStr = {
  marketing: 'مارکتینگ',
  campaigns: 'کمپین ها',
};

export const mainStr = {
  headTitle: 'AIBox',
  webTitle: 'AIBox',
  webDescription: 'توضیحات وب',
  or: 'یا',
  detailMore: 'توضیحات بیش‌تر',
  underDevelop: 'در حال توسعه',
};

// STATUS REPORT
export const statusReport = {
  listOfWithdrawals: 'لیست برداشت‌ها',
  staticInfo:
    'درخواست برداشت مبلغ 500,000 ریال با موفقیت ثبت و در دست اقدام قرار داده شد.',
  staticTitle: 'عنوان: برداشت اعتبار با انجام تراکنش بانکی',
  staticRequestTime: 'زمان درخواست: 14:23 1400/03/08',
  staticRemainingCredit: 'اعتبار باقی مانده: 150,000 ریال',
  staticDeposits:
    'واریز‌ها تا 72 ساعت پس از درخواست و در دو نوبت 9:00 و 15:00 انجام می‌شود.',
};

// PACKAGES
export const packagesString = {
  show: 'نمایش',
  noShow: 'عدم نمایش',
  packagesWasDeleted: 'بسته حذف شد',
  addNewPackage: 'افزودن بسته جدید',
  editPackage: 'ویرایش بسته',
  packageName: 'نام بسته',
  oneMonth: 'یک ماه',
  threeMonth: 'سه ماه',
  sixMonth: 'شش ماه',
  nineMonth: 'نه ماه',
  oneYear: 'یک سال',
  storageMemoryGb: 'حافظه ذخیره‌سازی(GB)',
  packageEntrancePrice: 'قیمت ورودی بسته(ریال)',
  maximumApiCallsPerDay: 'بیشینه تعداد فراخوانی API در هر روز',
  showInShoppingList: 'نمایش در لیست خرید:',
  userIsInUse: 'کاربر در حال استفاده هستند',
  createdIn: 'ایجاد شده در',
};

// INVITATION
export const invitationString = {
  newInvitationCodeAdded: 'کد دعوت جدید اضافه شد',
  insertingActivePackageRequired: 'درج بسته فعال ضروریست',
  invitationEn: 'Invitation',
  doneSuccessfully: 'با موفقیت انجام شد.',
  issueDate: 'تاریخ صدور',
  useDate: 'تاریخ استفاده',
  endOfCredit: 'پایان اعتبار',
  exDate: 'تاریخ انقضا',
  invitationCode: 'کد دعوت',
  addInvitationSuccess: 'ثبت کد دعوت جدید با موفیت انجام شد.',
};

// DISCOUNT CODE
export const discountCodeString = {
  remove: 'حذف کردن',
  edit: 'ویرایش کردن',
  createNewGiftCode: 'ایجاد کد هدیه جدید',
  newGiftCodeAdded: 'کد هدیه جدید اضافه شد..',
  giftCodeHasBeenRemoved: 'کد هدیه مورد نظر حذف شد.',
  addingNewGiftCodeWasSuccess: 'افزودن کد هدیه جدید با موفقیت انجام شد.',
  code: 'کد',
  insertCodeIsRequired: 'درج کد ضروریست',
  creditAmountRequired: 'درج مقدار اعتبار ضروریست.',
  expirationDateRequired: 'درج تاریخ انقضا ضروریست.',
  numberUsed: 'تعداد استفاده شده',
  codeTitle: 'عنوان کد',
  numOfAllCapacity: 'تعداد کل ظرفیت',
  removeDiscountCodeTitle: 'آیا مطمئن هستید؟',
  removeDiscountCoeeDescription:
    'با حذف کد هدیه امکان دسترسی به آن دیگر وجود نخواهد داشت.',
  maxCodeLength: 'حداکثر ۱۰ کاراکتر میتوانید وارد کنید.',
  minimumAmount: 'این مقدار باید بزرگتر یا مساوی یک باشد.',
  maximumAmount: 'حداکثر تا ۵۰ میلیون میتوانید وارد کنید.',
  maxAllowedUse: 'حداکثر تعداد کل ظرفیت ۱۰۰۰ می‌باشد.',
  maxFunction: (value: any) => `این مقدار باید کمتر از ${value} باشد.`,
  minFunction: (value: any) => `این مقدار باید بزرگتر از ${value} باشد.`,
};

// FINANCE TRANSACTION
export const financeTransaction = {
  financeAndTransaction: 'امور مالی و تراکنش‌ها',
  transactionTime: 'زمان تراکنش',
  transactionNumber: 'شماره تراکنش',
  transactionStatus: 'وضعیت تراکنش',
};

// USER STATUS
export const userStatus = {
  deleteUser: 'حذف کاربر؟',
  deleteModalInfo: 'با حذف کاربر دیگر امکان دسترسی به آن وجود نخواهد داشت.',
  userStatus: 'وضعیت کاربر',
  totalUsers: 'کل کاربران',
  activeUsers: 'کاربران فعال',
  newUsers: 'کاربران جدید',
  projectName: 'نام پروژه',
  done: 'انجام شده',
  closePage: 'بستن صفحه',
  createNewNotebook: 'ایجاد نوت بوک جدید',
};

// PACKAGE
export const dashboardPackage = {
  tariffsAndPackageSpecifications: 'تعرفه و مشخصات بسته‌ها',
  yourPackage: 'بسته شما',
  changePackageModalInfo:
    'با تغییر بسته، بسته مورد استفاده شما لغو می‌شود و امکان بازگشت فراهم نخواهد بود.',
  selectedPackageSuccessfullyRegistered: 'بسته انتخابی با موفقیت ثبت گردید.',
  finalizePackageOrder: 'نهایی کردن سفارش بسته',
  finalizeTheOrder: 'نهایی کردن سفارش',
  notEnoughCreditForPurchase:
    'اعتبار حساب شما کافی نیست! برای خرید بسته، حساب خود را شارژ کنید.',
  viewFullAdditionalDescription: 'نمایش کامل توضیحات تکمیلی',
  currentCredit: 'اعتبار فعلی',
  incrementalCreditAmount: 'مقدار اعتبار افزایشی',
  gift: 'هدیه',
  paymentInfo:
    'درصورتی که به دلیل مشکلات احتمالی در پرداخت های آنلاین، خرید شما ثبت نگردد مبلغ کسر شده حداکثر تا 72 ساعت بعد به حساب شما عودت داده خواهد شد.',
  completePurchaseInfo:
    'مشترک گرامی، لطفا پس از عملیات پرداخت روی کلید تکمیل فرآیند خرید کلیک کنید و جهت اطمینان از ثبت خریدتان به قسمت فاکتورها مراجعه نمایید.',
  creditIncreaseSuccessful: 'افزایش اعتبار با موفقیت انجام شد.',
  transactionNumber: 'شماره تراکنش',
  toBeSureInfo:
    'جهت اطمینان از ثبت و مشاهده اطلاعات خرید به قسمت فاکتورها مراجعه نمایید.',
  paymentWillNotBeSuccessfulInfo:
    'در صورت برداشت از حساب ، مبلغ کسر شده حداکثر تا 72 ساعت بعد به حساب شما عودت داده خواهد شد.',
  returnToDashboard: 'بازگشت به صفحه داشبورد',
  serverErrorEn: 'service error',
  yourConsumption: 'مصرف شما',
  creditUsed: 'اعتبار مصرف شده',
  CostOfUsingGraphicComputing: 'هزینه استفاده از رایانش گرافیکی',
  callServices: 'هزینه فراخوانی‌ها',
  day: 'روز',
};

export const dataFake = {
  stringArray: ['شماره یک', 'شماره دو', 'شماره سه'],
};

export const campaignStr = {
  editCampaign: 'ویرایش کمپین',
  addCampaign: 'اضافه کردن کمپین جدید',
  deleteModalTitle: 'حذف کمپین؟',
  deleteModalDetails: 'با حذف کمپین دیگر امکان دسترسی به آن وجود نخواهد داشت',
  campaignName: 'متن ورودی',
  startEvent: 'آغاز برگزاری',
  endEvent: 'پایان برگزاری',
  label: 'لیبل',
  campaignType: 'نوع کمپین',
  description: 'توضیحات',
  campaigns: 'کمپین ها',
  createDate: ' تاریخ ایجاد',
  campaign: 'کمپین',
  campainTitleError: 'لطفا عنوان را بدرستی وارد کنید.',
  campainDescriptionError: 'لطفا توضیحات را به درستی وارد کنید.',
};

export const filterTable = {
  refresh: 'نوسازی صفحه',
  manageColumns: 'مدریت ستون‌ها',
  filtering: 'فیلتر کردن',
  charts: 'نمودار‌ها',
  table: 'جدول',
  searching: 'جست و جو کنید ...',
  manageColumnsTitle:
    'باتوجه به نیاز خود می‌توانید ترتیب چینش ستون‌ها را تغییر داده و نمایش آن‌ها را کنترل کنید.',
  freezButtonTooltip: 'فیکس شدن در هنگام اسکرول',
};

export const btnStr = {
  send: 'ارسال',
  delete: 'حذف',
  cancel: 'لفو',
};

// PROFILE
export const profile = {
  imageProfileTitle: 'تصویر پروفایل',
  nickNameModalDes:
    'نام مستعار شما به عنوان برند شما در API Market استفاده می‌شود و قابل تغییر نیست، لذا در انتخاب آن دقت کافی را داشته باشید.',
  gpuPackage: 'بسته GPU:',
  ApiPackage: 'بسته API:',
  registeredApi: 'API ثبت شده :',
  UserAccountInformation: 'اطلاعات حساب کاربری',
  changePassword: 'تغییر گذرواژه',
  deletConfirlDescription:
    'با حذف این حساب دیگر امکان دسترسی به آن وجود نخواهد داشت.',
  deletConfirlTitle: 'حذف حساب؟',
  userProfile: 'مشخصات کاربری',
  securitySettings: 'تنظیمات امنیتی',
  male: 'مرد',
  female: 'زن',
  successMessage: 'مشخصات با موفقیت تغییر یافت.',
  uploadPhoto: 'آپلود عکس',
  emailAddress: 'آدرس ایمیل',
  emailAddressRequired: 'درج آدرس ایمیل الزامیست.',
  lastName: 'نام خانوادگی',
  lastNameRequired: 'درج نام خانوادگی الزامیست.',
  phoneNumber: 'شماره موبایل',
  phoneNumberRequired: 'درج شماره موبایل الزامیست.',
  nickName: 'نام مستعار',
  nickNameMustBeEnglish: 'نام مستعار باید انگلیسی باشد.',
  spaceIsNotAllowed: 'فاصله مجاز نیست.',
  gender: 'جنسیت',
  profileRegistration: 'ثبت مشخصات',
  editProfile: 'ویرایش مشخصات',
  submitInformation: 'ثبت اطلاعات',
  editInformation: 'ویرایش اطلاعات',
  thereIsNoActivePackage: 'بسته فعال وجود ندارد.',
  chooseYourPackageInfo:
    'برای بهره‌مندی از تمام امکانات سایت، بسته خود را انتخاب کنید. (رایگان)',
  numberOfGiftCallsLeft: 'تعداد فراخوانی هدیه باقی‌مانده',
  remainingTime: 'زمان باقی‌مانده',
  numberOfGiftCallsLeftNumber: '/10',
  changePasswordSuccessful: 'کلمه عبور با موفقیت تغییر یافت.',
  oldPassword: 'گذرواژه قدیم',
  oldPasswordRequired: 'درج کلمه عبور قدیم الزامیست.',
  newPass: 'گذرواژه جدید',
  newPassRequired: 'درج کلمه عبور جدید الزامیست.',
  ReNewPass: 'تکرار گذرواژه جدید',
  noBankAcountRegistered: 'تاکنون اطلاعاتی از حساب بانکی شما ثبت نشده است.',
  addNewAccount: 'افزودن حساب جدید',
  myBankAccount: 'حساب‌های بانکی من',
  account: 'حساب',
  qarzAlHasane: 'قرض‌الحسنه',
  wantToDeleteAccount:
    'با حذف شماره حساب تمامی اطلاعات مرتبط با آن از بین خواهد رفت.',
  wantToDeleteAccountTitle: 'حذف شماره حساب؟',
  no: 'خیر',
  accountSuccessfullyAdded: 'حساب با موفقیت افزوده شد.',
  bankName: 'نام بانک',
  bankNameRequired: 'درج نام بانک الزامیست.',
  accountNumberRequired: 'درج شماره حساب الزامیست.',
  accountNumberShouldNotBeZero: 'شماره حساب معتبر نیست.',
  shabaNumberTwentyTwoDigits: 'شماره شبا(22 رقم)',
  shabaNumberRequired: 'درج شماره شبا الزامیست.',
  shabaNumberNotValid: 'شماره شبا معتبر نیست.',
  cardNumberRequired: 'درج شماره کارت الزامیست.',
  cardNumberNotValid: 'شماره کارت معتبر نیست.',
  createdIn: 'ایجاد شده در',
  securitySettingInfo:
    'برای مدیریت کاربران و احراز هویت در هنگام فراخوانی APIها، شناسه API Key به‌صورت منحصربفرد برای هر کاربر تعریف می‌شود. محاسبات مالی مربوط به فراخوانی‌ها از طریق این شناسه انجام می‌شود؛ لذا از افشای آن خودداری کنید. درصورت لزوم می‌توان از بخش تنظیمات امنیتی پروفایل، نسبت به تغییر این شناسه اقدام کرد.',
  changeApiKey: 'تغییر API Key',
  numberOfUnTimedPackages: 'تعداد بسته‌های بدون زمان',
  numberOfMonthlyPackages: 'تعداد بسته‌های ماهانه',
  deleteModalDescription: 'با حذف، اطلاعات حساب شما از بین خواهد رفت.',
  maxAccountNumber: 'شماره حساب حداکثر 17 رقم می‌باشد.',
  maxShabaNumber: 'شماره شبا حداکثر 24 رقم می‌باشد.',
  maxCardNumber: 'شماره کارت حداکثر 16 رقم می‌باشد.',
  noActivePackageFound: 'بسته فعالی موجود نیست',
  notRegistered: 'ثبت نشده',
  WrongCardNumber: 'شماره کارت شما معتبر نیست.',
  WrongShabaNumber: 'شماره شبا وارد شده معتبر نیست.',
  WrongAccountNumber: 'شماره حساب شما معتبر نیست.',
  editUserInfo: 'ویرایش اطلاعات حساب کاربری',
};

/** ********** CONTACTUS START ********** */
export const contactUsSrt = {
  introBannerTitle: 'مشتاقانه آماده رفع سؤالات شما هستیم',
  introBannerDescription:
    'همراهان عزیز AIBox، اگر استفاده خاصی مورد نظر شماست و یا دغدغه و پرسشی ذهن شما را مشغول کرده است، می‌توانید با تکمیل کردن فرم مربوطه، با کارشناسان ما در ارتباط باشید.',
  formTitle: 'ارتباط با ما',
  formParagraph:
    'لطفاً پیش از ارسال پیام و یا تماس تلفنی، ابتدا قسمت سؤالات متداول را بررسی کنید.',
  formModalMessage:
    'کارشناسان ما در سریع‌ترین زمان ممکن درخواست شما را بررسی و نتیجه را به شما اعلام خواهند کرد.',
  addressTitle: 'نشانی و راه‌های ارتباطی',
  phone_1: '021-28425708',
  phone_2: '021-28426908',
  address:
    'تهران- خیابان کارگر شمالی- بالاتر از جلال آل احمد- دانشکده فنی دانشگاه تهران- نکسترا',
  email: 'info@nextaibox.com',
  hoursOfWork: 'یکشنبه تا پنجشنبه از ساعت 8 الی 16',
  support: 'پشتیبانی هفت روز هفته، 24 ساعت',
  description:
    'توجه داشته باشید که 28426908-021 و 28425708-021 تنها شماره‌هایی هستند که از طریق آن با کاربران و مشتریان تماس برقرار خواهد شد. بنابراین هرگونه تماس تحت عنوان ای آی باکس، با هر شماره‌ دیگری تخلف و سوء استفاده از نام تجاری AIBox است. لطفا برای پیگیری قانونی، آن را از طریق مسیرهای ارتباطی به کارشناسان پشتیبانی AIBox اطلاع دهید.',
};

// LABEL TEXT FIELD
export const labelTextField = {
  firstNameAndLastName: 'نام و نام خانوادگی',
  subjectOfRequest: 'موضوع درخواست',
  phoneNumber: 'شماره تماس',
  requestText: 'متن درخواست',
};
export const errorMessageTextField = {
  enterFullName: 'نام و نام‌خانوادگی خود را وارد کنید.',
  persianFirstAndLastName: 'نام و نام‌خانوادگی خود را به فارسی وارد کنید.',
  chooseYourSubject: 'موضوع را انتخاب کنید.',
  enterYourEmail: 'ایمیل خود را وارد کنید.',
  enterThePhoneNumber: 'شماره تلفن خود را وارد کنید.',
  charactersAllowedIs_1000: 'حداکثر 1000 کاراکتر مجاز است.',
};
export const message = {
  sendSuccessfully: 'پیام شما با موفقیت ارسال شد.',
  tokenInvalid: 'توکن اشتباه می‌باشد.',
};

// GPU SERVERS
export const gpuServersString = {
  userName: 'نام کاربر',
  gpuPackageName: 'نام بسته GPU',
  requestTime: 'زمان درخواست',
  reservationTime: 'زمان تخصیص',
  reservationEndTime: 'زمان اتمام رزرو',
  inQueue: 'در صف',
  canceled: 'لغو شده',
  expiredReservation: 'اتمام زمان رزرو',
  readyTime: 'در انتظار شروع',
  startingTime: 'در حال راه‌اندازی',
  stopped: 'متوقف شده',
  systemError: 'خطای فنی',
  gpuPackage: 'بسته GPU',
  servers: 'سرورها',
  requestTimeFrom: 'زمان درخواست از',
  requestTimeUpTo: 'زمان درخواست تا',
  reservationTimeFrom: 'زمان تخصیص از',
  reservationTimeUpTo: 'زمان تخصیص تا',
  startingTimeFrom: 'زمان شروع از',
  startingTimeUpTo: 'زمان شروع تا',
  users: 'کاربران',
};

export const commonWords = {
  grouping: 'گروه‌بندی',
  userName: 'نام کاربری',
  fullName: 'نام و نام خانوادگی',
  showVideo: 'نمایش ویدئو',
  panelAddress: 'آدرس پنل',
  inputData: 'داده ورودی',
  choosenValue: 'موقعیت انتخاب شده:',
  addressname: 'نام موقعیت',
  locationList: 'لیست موقعیت ها',
  addNewLocation: 'افزودن موقعیت جدید',
  currentLocation: 'موقعیت های تعریف شده',
  noResult: 'موردی یافت نشد.',
  required: 'پر کردن این فیلد اجباری است.',
  retry: 'تلاش مجدد',
  editEmail: 'ویرایش ایمیل',
  emailTest: 'تست ایمیل',
  smsTest: 'تست پیامک',
  add: 'افزودن',
  yes: 'بله',
  searchPlaceholder: 'نام، کدملی، پلاک، اشیاء و ...',
  describtion: 'توضیحات',
  apiDisplayStatus: 'وضعیت نمایش',
  editApi: 'ویرایش API',
  apiName: 'نام',
  apiCategory: 'دسته بندی',
  api: 'API',
  all: 'همه',
  editUser: 'ویرایش کاربر',
  addUser: 'افزودن کاربر',
  access: 'دسترسی',
  hour: 'ساعت',
  accesses: 'دسترسی‌ها',
  accountActivation: 'فعالسازی حساب کاربری',
  applyAccess: 'اعمال دسترسی',
  applyFilter: 'اعمال فیلتر',
  camera: 'دوربین',
  cameras: 'دوربین‌ها',
  camerasLocation: 'موقعیت دوربینها',
  cameraCount: 'تعداد دوربین',
  camerasCount: 'تعداد دوربین‌ها',
  cameraGrouping: 'گروه‌بندی دوربین',
  camerasGrouping: 'گروه‌بندی دوربین‌ها',
  cameraName: 'اسم دوربین',
  camerasList: 'لیست دوربین‌ها',
  locationName: 'آدرس',
  camerasOfThisGroup: 'دوربین‌های این گروه',
  category: 'دسته‌بندی',
  changeEmail: 'تغییر ایمیل',
  dashboard: 'داشبورد',
  disabled: 'غیرفعال',
  editDelete: 'ویرایش / حذف',
  edit: 'ویرایش',
  delete: 'حذف',
  action: 'عملیات',
  enabled: 'فعال',
  groupName: 'نام گروه',
  groupCount: 'تعداد گروه',
  groupsList: 'لیست گروه‌ها',
  time: 'ساعت',
  toTime: 'از ساعت',
  fromTime: 'تا ساعت',
  loading: 'در حال بارگذاری',
  place: 'مکان',
  row: 'ردیف',
  lng: 'طول جغرافیایی',
  lat: 'عرض جغرافیایی',
  sectionName: 'نام بخش',
  status: 'وضعیت',
  scenario: 'جریان کاری',
  totalCameras: 'کل دوربین‌ها',
  workflowCount: 'تعداد جریان کاری',
  workflowsCount: 'تعداد جریانهای کاری',
  scenarios: 'جریانهای کاری',
  technicalInfo: 'اطلاعات فنی',
  userAndAccessLevels: 'کاربران و سطوح دسترسی',
  deletSearch: 'آیا از حذف این گزینه مطمئن هستید؟',
  savedSearch: 'جست‌وجو های ذخیره شده',
  search: 'جست‌وجو',
  uploadFile: 'آپلود عکس',
  notSelected: 'فایلی انتخاب نشده',
  selectFile: 'انتخاب فایل',
  centimeter: 'سانتی متر',
  foundInfo: 'اطلاعات شناسایی شده',
  frameInfo: 'اطلاعات فریم',
  videoInfo: 'اطلاعات ویدئو',
  farsiName: 'نام فارسی',
  englishName: 'نام انگلیسی',
  shortName: 'نام اختصاری',
  method: 'متد',
  group: 'گروه',
  workflowGroup: 'جریان کاری گروه',
  general: 'عمومی',
  generalSetting: 'تنظیمات عمومی',
  Advanced: 'پیشرفته',
  advancedSetting: 'تنظیمات پیشرفته',
  similarityPercentage: {
    gte: 'درصد شباهت از',
    lte: 'درصد شباهت تا',
    defaultValue: 'درصد شباهت',
  },
  similarity: 'شباهت',
  active: 'فعال',
  deactive: 'غیرفعال',
  searchName: 'نام جست‌وجو',
  searchResult: 'نتیجه جست‌وجو',
  saveSearchSettings: 'ذخیره تنظیمات جست‌وجو',
  state: 'استان',
  city: 'شهر',
  date: 'تاریخ',
  fromDate: 'از تاریخ',
  toDate: 'تا تاریخ',
  filter: 'فیلتر',
  workflow: 'جریان کاری',
  workflows: 'جریان های کاری',
  startNodeName: 'داده ورودی ویدیو',
  wordNotFound: 'عبارت مورد نظر یافت نشد',
  otherWord: 'لطفا عبارت دیگری را جست‌وجو کنید',
  backToSearch: 'بازگشت به صفحه جست‌وجو',
  noWord: 'عبارت ناموجود',
  logoutMsg: 'آیا برای خروج مطمئن هستید؟',
  connectRoutes: 'اتصال مسیرها',
  notificationTitle: 'عنوان اعلان',
  notification: 'اعلان',
  notificationType: 'نوع اعلان',
  manageNotification: 'مدیریت اعلان',
  moreInformation: 'اطلاعات بیشتر',
  inDevelopment: 'در حال توسعه ...',
  indevelopmentDetail: 'صفحه مورد نظر در حال توسعه است',
  rowPerPage: 'سطر در هر صفحه: ',
  capSize: 'حداکثر حجم فایل (۵۰۰ مگابایت)',
  dragDrop: 'فایل را بکشید و رها کنید یا کلیک کنید',
  profileManagement: 'مدیریت پروفایل',
  exit: 'خروج',
  searchNoResult: 'نتیجه‌ای یافت نشد!',
  formatNotCorrect: 'فرمت فایل انتخابی غیرمجاز است',
  userCount: 'تعداد کاربران',
  alertEmail: 'ایمیل',
  emailPass: 'گذرواژه ایمیل',
  samePassword: 'تکرار گذرواژه با گذرواژه مطابقت ندارد',
  port: 'پورت',
  host: 'هاست',
  defaultEmail: 'ایمیل پیش فرض',
  TSL: 'TLS',
  SSL: 'SSL',
  alerts: 'اعلان ها',
  defaultProvider: 'ارائه دهنده پیش فرض',
  provider: 'ارائه دهنده',
  name: 'نام',
  address: 'آدرس',
  number: 'شماره',
  emailName: 'ایمیل',
  textTemp: 'الگوی متنی',
  alertSetting: 'لیست اعلان',
  alertHistory: 'تاریخچه اعلان',
  phoneSetting: 'تنظیمات موبایل',
  textArea: 'کلید ها(اطلاعات وارد شده فرمت Json باشد)',
  sendLocation: 'ارسال موقعیت',
  locationTime: 'مدت زمانی که موقعیت کاربر برای سرور ارسال می شود',
  sendVideo: 'فیلم های ارسالی',
  videoTime: 'مدت زمان فیلم های ارسالی از طرف کاربران موبایل',
  email: 'ایمیل',
  sms: 'پیامک',
  userStatus: 'وضعیت  گروه',
  addLocation: 'افزودن موقعیت',
  editLocation: 'ویرایش موقعیت',
  addUserGroup: 'افزودن گروه کاربری',
  details: 'جزئیات',
  userDetail: 'جزئیات کاربر',
  addTempStr: 'افزودن متن',
  textTempName: 'نام متن',
  addEmail: 'افزودن ایمیل',
  serviceType: 'نوع سرویس',
  userGroup: 'گروه کاربری',
  defaultText: 'متن پیش فرض',
  users: 'کاربران',
  deleteTextTemp: 'آیا برای حذف این متن مطمئن هستید؟',
  addTextWarning:
    'پیام خود را بصورت << متن دلخواه ٪٪ متن دلخواه ٪٪ متن دلخواه >> بنویسید. در این الگو، ٪٪ اول تاریخ و ٪٪ دوم شناسه جست‌وجو است.',
  addTextPlacholder: 'الگوی متنی ...',
  addAlert: 'افزودن اعلان',
  editAlert: 'ویرایش اعلان',
  selectSms: 'انتخاب پیامک',
  selectEmail: 'انتخاب ایمیل',
  notJson: 'متن باید به صورت JSON باشد (مثال: { "key" : "value" })',
  usedCameraChart: 'نمودار استفاده از دوربین در جست‌وجو',
  usedWorkflowChart: 'نمودار استفاده از جریان های کاری در جست‌وجو',
  latestUsers: 'آخرین کاربران',
  cameraPanelUsername: 'نام کاربری پنل دوربین',
  cameraModel: 'مدل دوربین',
  phoneNum: 'شماره همراه',
  emailAddress: 'آدرس ایمیل',
  companyName: 'نام شرکت',
  chooseLocation: 'یک نقطه را روی نقشه انتخاب کنید',
  picture: 'تصویر',
  deleteUser: 'آیا از حذف این کاربر اطمینان دارید؟',
  accessAndPermissionToGroup:
    'برای افزودن سطح دسترسی گروه، به بخش گروه‌بندی مراجعه کنید.',
  addGroup: 'افزودن گروه',
  editGroup: 'ویرایش گروه',
  generalInfo: 'مشخصات عمومی',
  loadingText: 'لطفا شکیبا باشید',
  virtualFence: 'فنس مجازی',
};

export const usersStr = {
  userGroup: 'گروه کاربری',
  deleteGroup: 'آیا از حذف این گروه مطمئن هستید؟',
  deleteOption: 'آیا از حذف این گزینه مطمئن هستید؟',
  askSwitchStatus: 'آیا از تغییر وضعیت این کاربر مطمئن هستید؟',
  usersList: 'لیست کاربران',
  joinDate: 'تاریخ عضویت',
  groups: 'گروه ها',
  phone: 'تلفن همراه',
  nationalId: 'کد ملی',
  email: 'ایمیل',
  accessLevel: 'سطح دسترسی',
  fullName: 'نام و نام‌خانوادگی',
  selectUserGroup: 'انتخاب گروه های کاربر',
  dashboard: 'داشبورد',
  grouping: 'گروه و سطح دسترسی',
  api: 'API',
  camera: 'دوربین',
  scenario: 'جریان کاری',
};

export const deleteMessages = {
  defaultDeleteMsg: 'آیا برای حذف این دوربین مطمئن هستید؟',
  deleteAlert: 'آیا برای حذف این اعلان مطمئن هستید؟',
  deleteEmail: 'آیا برای حذف این ایمیل مطمئن هستید؟',
  deleteSms: 'آیا برای حذف این پیامک مطمئن هستید؟',
  deleteWorkflow: 'آیا برای حذف این جریان کاری مطمئن هستید؟',
  deleteLocation: 'آیا برای حذف این موقعیت مطمئن هستید؟',
  deleteCameraGroup: 'آیا برای حذف این گروه بندی مطمئن هستید؟',
  deleteUserGroup: 'آیا برای حذف این گروه کاربری مطمئن هستید؟',
};

export const siderBarList = {
  dashboard: 'دشبورد',
  informationBank: 'بانک اطلاعاتی',
  supervisitoryList: 'لیست نظارتی',
  imageRecognition: 'شناسایی تصویر',
  report: 'گزارشات',
  trafficAnalysis: 'آنالیز تردد',
  userManagement: 'کاربران',
  setting: 'تنظیمات',
};

export const ReportModal = {
  name: 'نام گیت',
  sex: 'جنسیت',
  arow: 'جهت گیت',
  bithCity: 'محل تولد',
  age: 'سن',
  agreementPercent: 'درصد تطابق',
  date: 'زمان ثبت',
  results: 'نتایج شناسایی',
};

export const DataBankRoute = {
  addGroupFormTitle: 'افزودن گروه',
  groupInformation: 'اطلاعات گروه',
  add: 'افزودن',
  mobile: 'تلفن همراه',
  phone: 'تلفن ثابت',
  education: 'تحصیلات',
  sex: 'جنسیت',
  birthDate: 'تاریخ تولد',
  birthCity: 'محل تولد',
  placeOfIssue: 'محل صدور',
  birthCertificateNumber: 'شماره شناسنامه',
  fatherName: 'نام پدر',
  lastName: 'نام‌خانوادگی',
  firstName: 'نام',
  uploadImage: 'بازگذاری تصاویر',
  addGropModalTitle: 'افزودن گروه',
  generalKnowledge: 'اطلاعات عمومی',
  information: 'توضیحات',
  address: 'آدرس',
  infoDialog: 'متن راهنما پیش‌فرض',
  personalInfo: 'اطلاعات شخصی',
  addSingleUserTitle: 'ثبت نام انفرادی',
  usersList: 'لیست افراد',
  groupList: 'لیست گروه',
  name: 'نام و نام‌خانوادگی',
  nationalId: 'کد ملی',
  phoneNumber: 'شماره موبایل',
  group: 'گروه',
  nationality: 'ملیت',
  supervisortList: 'لیست نظارتی',
  groupName: 'نام گروه',
  description: 'توصیف',
  deleteModalRedText: 'این عمل برگشت ناپذیر است',
  deleteModalBlackText: 'آیا برای حذف این گزینه مطمئن هستید ؟',
  filter: 'فیلتر',
  earase: 'پاک‌سازی',
};
