import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider as MuiThemeProvider } from '@mui/material/styles';
import { Snackbar } from '@/components/atoms/SnackBar/notification';
import theme from '@/theme';
import { ReactQueryProvider } from '@/providers';

const myFont = localFont({
  display: 'swap',
  src: [
    {
      path: '../../public/fonts/iranyekanweblightfanum.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iranyekanwebregularfanum.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/iranyekanwebboldfanum.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-iran-yekan',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={myFont.variable}>
      <body>
        <ReactQueryProvider>
          <AppRouterCacheProvider>
            <MuiThemeProvider theme={theme}>
              {children}
              <Snackbar />
            </MuiThemeProvider>
          </AppRouterCacheProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
